// Generated by CoffeeScript 1.6.2
(function() {
  var Build, NoJam, PackageManagers, outcome;

  PackageManagers = require("./packageManagers");

  Build = require("./build");

  outcome = require("outcome");

  NoJam = (function() {
    /*
    */
    function NoJam(ops) {
      this._packageManager = new PackageManagers();
      this._build = new Build(ops, this._packageManager);
    }

    /*
    */


    NoJam.prototype.rebuild = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this._build.run(callback);
    };

    /*
    */


    NoJam.prototype.install = function(packages, callback) {
      var _this = this;

      return this._packageManager.install(packages, function() {
        return _this.rebuild(callback);
      });
    };

    return NoJam;

  })();

  module.exports = NoJam;

}).call(this);
