// Generated by CoffeeScript 1.6.2
(function() {
  var spawn, toarray;

  spawn = require("child_process").spawn;

  toarray = require("toarray");

  module.exports = (function() {
    /*
    */
    function _Class(binName) {
      this.binName = binName;
    }

    /*
    */


    _Class.prototype.install = function(packages, cb) {
      return this._exec(["install"].concat(packages), cb);
    };

    /*
    */


    _Class.prototype.upgrade = function(cb) {
      return this._exec(["upgrade"], cb);
    };

    /*
    */


    _Class.prototype.clearCache = function() {
      return this._exec(["clear-cache"], cb);
    };

    /*
    */


    _Class.prototype._exec = function(args, callback) {
      var proc,
        _this = this;

      proc = spawn(this.binName, args);
      proc.stdout.on("data", function(chunk) {
        return process.stdout.write(chunk);
      });
      proc.stderr.on("data", function(chunk) {
        return process.stderr.write(chunk);
      });
      return proc.on("exit", function(code) {
        if (code) {
          return callback(new Error("" + _this.binName + " " + args[0] + " exited with code " + code));
        }
        return callback();
      });
    };

    return _Class;

  })();

}).call(this);
