// Generated by CoffeeScript 1.4.0
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class() {
      _Class.__super__.constructor.call(this, "jam");
    }

    /*
    */


    _Class.prototype.rebuild = function(cb) {
      return this._exec(["rebuild"], cb);
    };

    /*
    */


    _Class.prototype.clearCache = function(cb) {
      return this._exec(["clear-cache"], cb);
    };

    return _Class;

  })(Base);

}).call(this);
